[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pytrader"
version = "0.0.3"
description = "Trading Application"
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE.md"}
keywords = []
authors = [
  { name = "G Derber", email="gd.github@radiantendeavors.com" },
]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Programming Language :: Python",
  "License :: OSI Approved :: GNU Affero General Public License v3"
]

dependencies = [
 "appdirs >= 1.4.4",
 "attrs >= 22.2.0",
 "beautifulsoup4 >= 4.11.1",
 "cattrs >= 22.2.0",
 "certifi >= 2022.12.7",
 "cffi >= 1.15.1",
 "charset-normalizer >= 3.0.1",
 "cryptography >= 39.0.0",
 "exceptiongroup >= 1.1.0",
 "frozendict >= 2.3.4",
 "html5lib >= 1.1",
 "ibapi >= 9.81",
 "idna >= 3.4",
 "lxml >= 4.9.2",
 "multitasking >= 0.0.11",
 "numpy >= 1.24.1",
 "pandas >= 1.5.3",
 "polygon-api-client >= 1.6.2",
 "pycparser >= 2.21",
 "PyMySQL >= 1.0.2",
 "python-dateutil >= 2.8.2",
 "pytz >= 2022.7.1",
 "PyYAML >= 6.0",
 "requests >= 2.28.2",
 "requests-cache >= 0.9.8",
 "six >= 1.16.0",
 "soupsieve >= 2.3.2.post1",
 "url-normalize >= 1.4.3",
 "urllib3 >= 1.26.14",
 "webencodings >= 0.5.1",
 "websockets >= 10.4",
 "yfinance >= 0.2.4"
]

[project.urls]
"Homepage" = "https://github.com/radiantendeavors/trading"
"Bug Tracker" = "https://github.com/radiantendeavors/trading/issues"

[project.scripts]
pytrader = "pytrader.ui.pytrader"
pytrdownload = "pytrader.ui.pytrdownload"
pytrdatabase = "pytrader.ui.pytrdatabase"
